# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH=$HOME/.oh-my-zsh

# You can change the theme with another one:
#   https://github.com/robbyrussell/oh-my-zsh/wiki/themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="powerlevel10k/powerlevel10k"


# Useful oh-my-zsh plugins
plugins=(
  zsh-syntax-highlighting
  zsh-autosuggestions
  git
  gitfast
  last-working-dir
  common-aliases
  zsh-history-substring-search
  you-should-use
  z
  web-search
  command-not-found
)

# Prevent Homebrew from reporting
export HOMEBREW_NO_ANALYTICS=1

# Do not keep cache for Homebrew
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=0

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)

# mise (Replaces rbenv, nvm, anaconda)
if [[ -x "$HOME/.local/bin/mise" ]]; then
  eval "$($HOME/.local/bin/mise activate zsh)"
fi

# Set common PATHs
# - Rails and Ruby uses the local `bin` folder to store binstubs.
# - node_modules/.bin for local JS tools
# - /usr/local/sbin for system tools
export PATH="./bin:./node_modules/.bin:$HOME/.local/bin:/usr/local/sbin:$PATH"

export TERMINFO_DIRS=/usr/share/terminfo:/opt/homebrew/opt/ncurses/share/terminfo

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR="code"
export BUNDLER_EDITOR="code"

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH".

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Fonction qui s'exécute juste avant d'afficher le prompt
set_terminal_title() {
  # %1~ affiche uniquement le dernier composant du chemin (le dossier actuel)
  echo -ne "\e]2;${PWD##*/}\a"
}

# Exécuter la fonction avant chaque affichage du prompt
add-zsh-hook precmd set_terminal_title
